### ISSUE TITLE
Pins 9-10?

### ISSUE THREAD

**Issue by clydemcqueen** [apl-ocean-engineering/aquarium_jetson_nano#1]
Typo in https://github.com/apl-ocean-engineering/aquarium_jetson_nano/wiki/Aaron-2024%E2%80%9010%E2%80%9014-Jetson-Bringup?

I think you meant to say pins 9-10, not 10-11.

**Comment by amarburg** [comment]
Keeping me on my toes!

Technically, could be either 9 or 11, just need to connect FORCE_RECOVERY (pin 10) to ground:

<img width="755" alt="image" src="https://github.com/user-attachments/assets/75fdbacc-3daf-4145-99fd-4461df4b1831">
